import { useEffect, useState } from 'react';
import { useOverwatchStore } from '../store/overwatch-store';

interface Order {
  id: string;
  orderId: string;
  orderType: string;
  effectiveStart?: string;
  effectiveEnd?: string;
  issuingAuthority?: string;
  atoDayNumber?: number;
  status?: string;
}

type OrderFilter = 'ALL' | 'ATO' | 'MTO' | 'STO';

export function OrdersView() {
  const activeScenarioId = useOverwatchStore((s) => s.activeScenarioId);
  const socket = useOverwatchStore((s) => s.socket);

  const [orders, setOrders] = useState<Order[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [activeFilter, setActiveFilter] = useState<OrderFilter>('ALL');

  // Fetch orders when scenario changes
  useEffect(() => {
    if (!activeScenarioId) {
      setOrders([]);
      return;
    }

    let mounted = true;
    const fetchOrders = async () => {
      setLoading(true);
      setError(null);
      try {
        const res = await fetch(`/api/orders?scenarioId=${activeScenarioId}`);
        const json = await res.json();
        if (!json.success) throw new Error(json.error || 'Failed to load orders');
        if (mounted) setOrders(json.data || []);
      } catch (err) {
        if (mounted) setError(String(err));
      } finally {
        if (mounted) setLoading(false);
      }
    };

    fetchOrders();
    return () => { mounted = false; };
  }, [activeScenarioId]);

  // WebSocket listener for new orders
  useEffect(() => {
    if (!socket) return;

    const handleOrderPublished = (data: any) => {
      setOrders(prev => {
        // Avoid duplicates
        if (prev.some(o => o.id === data.id)) return prev;
        return [...prev, data];
      });
    };

    socket.on('order:published', handleOrderPublished);
    return () => {
      socket.off('order:published', handleOrderPublished);
    };
  }, [socket]);

  // Filter orders by type
  const filteredOrders = activeFilter === 'ALL'
    ? orders
    : orders.filter(o => o.orderType === activeFilter);

  return (
    <>
      <div className="content-header">
        <h1>Tasking Orders</h1>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          {(['ATO', 'MTO', 'STO'] as const).map(type => (
            <button
              key={type}
              className={`btn btn-sm ${activeFilter === type ? 'btn-primary' : 'btn-secondary'}`}
              onClick={() => setActiveFilter(activeFilter === type ? 'ALL' : type)}
            >
              <span className={`badge badge-${type === 'ATO' ? 'air' : type === 'MTO' ? 'maritime' : 'space'}`}>
                {type}
              </span>
            </button>
          ))}
          <span style={{ color: 'var(--text-muted)', fontSize: '12px', paddingLeft: '8px' }}>
            {filteredOrders.length} order{filteredOrders.length !== 1 ? 's' : ''} loaded
          </span>
        </div>
      </div>

      <div className="content-body">
        <div className="card">
          <div className="card-header">
            <span className="card-title">Order Feed</span>
            <span className="text-xs text-muted">Orders stream in as simulation progresses</span>
          </div>
          <div className="card-body">
            {loading && (
              <div style={{ padding: '24px', textAlign: 'center', color: 'var(--text-muted)' }}>
                Loading orders...
              </div>
            )}

            {error && (
              <div style={{ padding: '24px', color: 'var(--accent-danger)' }}>
                Error: {error}
              </div>
            )}

            {!loading && !error && filteredOrders.length === 0 && (
              <div className="empty-state" style={{ padding: '48px' }}>
                <div className="empty-state-icon">📋</div>
                <div className="empty-state-title">No tasking orders received</div>
                <div className="empty-state-description">
                  Orders (ATO, MTO, STO) will appear here as they are generated by the simulation.
                  Each order contains mission packages with missions, targets, time windows, and support requirements.
                </div>
              </div>
            )}

            {!loading && !error && filteredOrders.length > 0 && (
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '12px' }}>
                <thead>
                  <tr style={{ borderBottom: '1px solid var(--border)', color: 'var(--text-muted)' }}>
                    <th style={{ padding: '8px 12px', textAlign: 'left' }}>Order ID</th>
                    <th style={{ padding: '8px 12px', textAlign: 'left' }}>Type</th>
                    <th style={{ padding: '8px 12px', textAlign: 'left' }}>ATO Day</th>
                    <th style={{ padding: '8px 12px', textAlign: 'left' }}>Effective Start</th>
                    <th style={{ padding: '8px 12px', textAlign: 'left' }}>Effective End</th>
                    <th style={{ padding: '8px 12px', textAlign: 'left' }}>Issuing Authority</th>
                    <th style={{ padding: '8px 12px', textAlign: 'left' }}>Status</th>
                  </tr>
                </thead>
                <tbody>
                  {filteredOrders.map(order => (
                    <tr key={order.id} style={{ borderBottom: '1px solid var(--border)' }}>
                      <td style={{ padding: '8px 12px', color: 'var(--text-bright)', fontFamily: 'var(--font-mono)' }}>
                        {order.orderId || order.id.slice(0, 8)}
                      </td>
                      <td style={{ padding: '8px 12px' }}>
                        <span className={`badge badge-${order.orderType === 'ATO' ? 'air' : order.orderType === 'MTO' ? 'maritime' : 'space'}`}
                          style={{ fontSize: '10px' }}>
                          {order.orderType}
                        </span>
                      </td>
                      <td style={{ padding: '8px 12px', color: 'var(--text-secondary)' }}>
                        {order.atoDayNumber ?? '--'}
                      </td>
                      <td style={{ padding: '8px 12px', color: 'var(--text-muted)', fontFamily: 'var(--font-mono)' }}>
                        {order.effectiveStart ? new Date(order.effectiveStart).toISOString().slice(0, 16) + 'Z' : '--'}
                      </td>
                      <td style={{ padding: '8px 12px', color: 'var(--text-muted)', fontFamily: 'var(--font-mono)' }}>
                        {order.effectiveEnd ? new Date(order.effectiveEnd).toISOString().slice(0, 16) + 'Z' : '--'}
                      </td>
                      <td style={{ padding: '8px 12px', color: 'var(--text-secondary)' }}>
                        {order.issuingAuthority || '--'}
                      </td>
                      <td style={{ padding: '8px 12px' }}>
                        <span style={{
                          fontSize: '10px', fontWeight: 600, padding: '2px 6px', borderRadius: '4px',
                          background: 'rgba(0,212,255,0.1)', color: 'var(--accent-primary)',
                        }}>
                          {order.status || 'PUBLISHED'}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        </div>
      </div>
    </>
  );
}
