export function OrdersView() {
  return (
    <>
      <div className="content-header">
        <h1>Tasking Orders</h1>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <button className="btn btn-sm btn-secondary">
            <span className="badge badge-air">ATO</span>
          </button>
          <button className="btn btn-sm btn-secondary">
            <span className="badge badge-maritime">MTO</span>
          </button>
          <button className="btn btn-sm btn-secondary">
            <span className="badge badge-space">STO</span>
          </button>
          <span style={{ color: 'var(--text-muted)', fontSize: '12px', paddingLeft: '8px' }}>
            0 orders loaded
          </span>
        </div>
      </div>

      <div className="content-body">
        <div className="card">
          <div className="card-header">
            <span className="card-title">Order Feed</span>
            <span className="text-xs text-muted">Orders stream in as simulation progresses</span>
          </div>
          <div className="card-body">
            <div className="empty-state" style={{ padding: '48px' }}>
              <div className="empty-state-icon">📋</div>
              <div className="empty-state-title">No tasking orders received</div>
              <div className="empty-state-description">
                Orders (ATO, MTO, STO) will appear here as they are generated by the simulation.
                Each order contains mission packages with missions, targets, time windows, and support requirements.
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
